/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ApiConsole: typeof import('./components/ApiConsole.vue')['default']
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    ContactForm: typeof import('./components/ContactForm.vue')['default']
    FooterBar: typeof import('./components/FooterBar.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    Hero: typeof import('./components/Hero.vue')['default']
    ProjectCard: typeof import('./components/ProjectCard.vue')['default']
    RepoGrid: typeof import('./components/RepoGrid.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TechChips: typeof import('./components/TechChips.vue')['default']
    ThemeToggle: typeof import('./components/ThemeToggle.vue')['default']
    Timeline: typeof import('./components/Timeline.vue')['default']
  }
}
